apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-c
  labels:
    app: api-service-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service-c
  template:
    metadata:
      labels:
        app: api-service-c
    spec:
      containers:
      - name: api-service-c
        image: michaelfriedman1/service_c:1.1
        ports:
        - containerPort: 5000